name: meliloti_nf

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - openjdk=17
  - nextflow=25.04.8
  - trim-galore=0.6.11
  - fastqc=0.12.1
  - cutadapt=5.2
  - multiqc=1.33
  - bbmap=38.99
  - salmon=1.10.2