name: meliloti_nf

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - nextflow=25.04
  - trim-galore=0.6
  - fastqc=0.12
  - cutadapt=5
  - multiqc=1.33
  - bbmap=38
  - salmon=1.11